### PR TITLE
Bump scalameta-parsers to 4.7.0

### PR DESCRIPTION
**Pull request by tanishiking**
I tested it locally, and I confirmed it works as I expected. (4.7.0 contains a bunch of bug fixes from the previous version).

astexplorer

### CODE REVIEW

**Comment by hugo-vrijswijk** [comment]
@fkling Could you take a look at this? :)

**Comment by kitbellew** [comment]
@tanishiking how to increase the version to 4.8.7?
@fkling is this something you can help merge and release?

**Comment by fkling** [comment]
Just merged it and bumped the version to v4.8.7. Thank you for the PR and sorry for neglecting it (and everything else here). I'm trying to bring everything up-to-date.

**Comment by tanishiking** [comment]
@fkling @kitbellew No worries! Thank you very much for maintaining this project and reviewing 🎉

**Pull request merged**
