### PR TITLE
Add Tenko to the hall of fame

### PR DESCRIPTION
**Pull request by pvdz**
Huzah

### CODE REVIEW

**Comment by fkling** [comment]
You can remove all the files in `packages/`, these are not needed. Any chance you can add the `yarn.lock` file to the PR?

**Comment by pvdz** [comment]
Updated to remove the packages. Unfortunately my local yarn cache is busted somehow and I've used npm-add to add it... :/ I can have a look tomorrow, I'll probably have to resolve the yarn cache integrity problem anyways. F.U.N.

**Comment by pvdz** [comment]
Fixed

**Comment by fkling** [comment]
Awesome!

**Comment by fkling** [comment]
You can already play around with it at https://staging.astexplorer.net .

**Pull request merged**
