### PR TITLE
Add support for "Handlebars" and the "Glimmer" parser

### PR DESCRIPTION
**Pull request by Turbo87**
screenshot

see https://github.com/tildeio/glimmer

also, greetings from Aachen 😉

### CODE REVIEW

**Comment by Turbo87** [comment]
screenshot

added support for the bare Handlebars parser too now

see https://github.com/wycats/handlebars.js

/cc @rwjblue

**Comment by Turbo87** [comment]
screenshot

and now we can also write Glimmer AST plugins :)

@fkling kudos on making this very easy to extend!!

**Comment by fkling** [comment]
That's awesome! I ❤️  new transform tools! I looked over the code and it all looks good to me. I will merge it later.

( 👋  back to Aachen and Germany! I officially studied at RWTH Aachen but all courses took place in Bonn. I've been to Aachen a couple of times though 😃  )

**Comment by RReverser** [comment]
> @RReverser made this a lot easier.

Thanks for the shout-out!

**Comment by fkling** [comment]
Had to fix a minor thing (2308633540c20de36053df73e1c00e1dc4bd2230) but everything seems to work now!

**Comment by Turbo87** [comment]
Awesome, thanks a lot for the quick response!

**Pull request merged**
