### PR TITLE
Add TypeScript option to Babylon 7

### PR DESCRIPTION
**Pull request by thejameskyle**
Resolves https://github.com/fkling/astexplorer/issues/267

### CODE REVIEW

**Comment by xtuc** [comment]
Flow annotations will collide with TypeScript syntax, it might be annoying for the peoples used to Flow in astexplorer.

What about two different parser? One _Babylon7-Flow_ with the Flow flag for Babylon and _Babylon7-TypeScript_ which would use the TypeScript flag.

**Comment by thejameskyle** [comment]
Only if you have both enabled which Babylon should throw an error which AST Explorer can handle as it does already. We should fix this on the Babylon side and leave AST Explorer (and any other consumer) with a simpler implementation.

**Comment by hzoo** [comment]
^ Babylon should already throw an error when you try to turn on both so this should be fine

**Comment by thejameskyle** [comment]
@fkling do you need anything for this?

**Comment by hzoo** [comment]
I think he may be out/busy still (vacation)?

**Comment by fkling** [comment]
I'll update everything tomorrow!

**Pull request merged**
