### PR TITLE
Add support for ICU messages and "intl-messageformat-parser"

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/yahoo/intl-messageformat-parser

### CODE REVIEW

**Comment by Turbo87** [comment]
unfortunately it has no support for location info in the node yet (see https://github.com/yahoo/intl-messageformat-parser/issues/16)

**Comment by fkling** [comment]
Thank you! I'm amazed what "languages" and parsers exist 😉 

Will merge this tonight.

**Comment by Turbo87** [comment]
Let's hope https://github.com/yahoo/intl-messageformat-parser/pull/17 is merged, then we'll have location information for the nodes too :)

**Comment by Turbo87** [comment]
@fkling thanks for merging :)

I noticed that the ICU icon is not showing up on the live site though. any ideas what's going on?

**Comment by fkling** [comment]
It seems to be a caching issue. A hard refresh made the icon appear for me. (caching in general is messed up, I hope this will become less of an issue with #197).

**Pull request merged**
