### PR TITLE
improve defaults for eslint transform

### PR DESCRIPTION
**Pull request by kentcdodds**
Ref #117 
I haven't actually tested this out but it seems like this would be the change to make until we add a UI to configure the transform...

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hmmm... Tried locally and this doesn't work. I'm not sure what's up :-(

**Comment by fkling** [comment]
Thanks for working on this! I'm currently a bit busy, but will take a closer look next week.

**Comment by fkling** [comment]
So, the problem is with the `parseNoPatch` method actually. That results in an error. The eslint setup is a bit weird, I will submit a new PR that fixes that issue and cleans eslint up.

Your changes are still needed though, so I will merge this. Thank you!

**Comment by kentcdodds** [comment]
Wahoo! Thank you for working on this!

**Pull request merged**
