### PR TITLE
babel-with-typescript

### PR DESCRIPTION
**Pull request by SukantPal**
#508

### CODE REVIEW

**Comment by fkling** [comment]
After revisiting this, I'm not sure why this is needed. You can already select `typescript` in the options of the existing parser... can you explain?

**Comment by SukantPal** [comment]
@fkling The "typescript" parser's AST is different from that of Babel.

**Comment by sibelius** [comment]
image

```jsx
const AppType = new GraphQLObjectType<IApp, GraphQLContext>({
  name: 'App',
  description: 'Represents a App',
  fields: () => ({
    id: globalIdField('App'),
    createdAt: {
      type: GraphQLString,
      resolve: (obj) => (obj.createdAt ? obj.createdAt.toISOString() : null),
    },
  }),
  interfaces: () => [NodeInterface],
});
```

this fails to parse using normal babel

if I switch to typescript it works, but it does not help if I'm working in codemods with jscodeshift that uses babel parser instead of typescript parser

**Comment by sibelius** [comment]
if you check prettier parsers https://prettier.io/docs/en/options.html#parser

they have a `babel`, `babel-flow` and `babel-ts`

**Comment by fkling** [comment]
I still don't understand why we need a separate entry for this. What is the problem with opening the settings and enabling the typescript option?

**Comment by sibelius** [comment]
I've missed the settings, it works great tks

**Comment by SukantPal** [comment]
@fkling I got it now. The "settings" button doesn't look separate from the parsers menu. This is a UI/UX/usability bug, I would say. I can close this PR, I guess then.

Screen Shot 2020-08-04 at 6 24 24 PM

**Comment by fkling** [comment]
@SukantPal Agreed that it's not the most obvious of places (but it's been like this for a long time). I'm working on a new design.

**Comment by yuzai** [comment]
this ui bug is confusing, I did't find the settings button until I saw this issue

**Pull request closed without merging**
