### PR TITLE
Update `@glimmer` packages to v0.30.2

### PR DESCRIPTION
**Pull request by Turbo87**
Addresses https://github.com/fkling/astexplorer/pull/245#issuecomment-344621867

Closes #245

/cc @rwjblue @fkling

### CODE REVIEW

**Comment by Turbo87** [comment]
@fkling it looks like the `simple-html-tokenizer` subdependency of `@glimmer/syntax` is not passed through Babel and so it still has ES6 code in it that throws when minified using UglifyJS. 

Any idea how to resolve this issue? I'm not exactly an expert on webpack 🤔

**Comment by fkling** [comment]
> Any idea how to resolve this issue?

Everything that should be passed through babel [is configured here](https://github.com/fkling/astexplorer/blob/816ac89bb02cb3e27e5b84e6019261a556282d09/website/webpack.config.js#L142-L163). It might be as simple as adding

```js
path.join(__dirname, 'node_modules', 'simple-html-tokenizer'),
```

**Comment by Turbo87** [comment]
@fkling indeed, that was all that was needed, thanks! :)

**Comment by fkling** [comment]
Merged locally.

**Pull request closed without merging**
