### PR TITLE
feat: implement a typescript transformer

### PR DESCRIPTION
**Pull request by kevinramharak**
This PR will implement the typescript transformer API. The existing infrastructure made it extremly easy to implement.

### CODE REVIEW

**Comment by kevinramharak** [comment]
NOTE: it does use some internal API's:
- The `ts.Writer` interface and `ts.createTextWriter` factory function
- The `ts.Printer` methods that write to this interface

There are no public API's available that implement these, and reimplementing them (copy & pasting) them seems like a wasted effort.

**Comment by kevinramharak** [comment]
@fkling Any feedback or comments? If not then can this be merged?

**Comment by fkling** [comment]
Mmh, I thought I has merged this in the meantime, but I guess not.

I just hope it's not going to be difficult to keep this maintained :)

**Comment by kevinramharak** [comment]
Thanks for the merge. Works well on production. I doubt the code will break anytime soon, im just taking a shortcut in the API to not have to run the whole bloated pipeline for a small piece of code. I'll take another look to see if I can find equivelent public api calls, but the emit api is a bit of a pain to work with to just run a single transformer on a piece of code.

The code using the internal API are these lines/statements:
```ts
    // createTextWriter(newline: string)
    const writer = ts.createTextWriter(host.getNewLine());

    // ...

    // printer is part of the public API, writeFile is marked as internal
    // writeFile(sourceFile: ts.SourceFile, writer: ts.EmitTextWriter, ...optional stuff)
    printer.writeFile(resultFile, writer, void 0);
    
    // technically these are part of the internal API, because they are dependent on the createTextWriter call
    const result = writer.getText();
    writer.clear();
```

**Comment by kevinramharak** [comment]
@fkling Turns out the public API does exactly what I did but its name and type declarations confused me. So the PR #579 should remove your concerns. Those calls are all part of the public api so it should address your concerns in maintainability.

**Pull request merged**
