### PR TITLE
Add prettier to JSCodeshiftEditor

### PR DESCRIPTION
**Pull request by lewisf**
This allows prettier to run on the JSCodeshiftEditor. I'm not sure if 'blur' is the right time to run this honestly but at the very least I'm wondering if it's worth adding prettier to astexplorer.net somehow (maybe as a togglable option?). I definitely currently spend a lot of time just formatting code within the in-browser editor.

### CODE REVIEW

**Comment by fkling** [comment]
I can definitely see value in having an option for it, but I don't think enabling this behavior by default is a good idea. I could imagine there quite a lot of people that don't use prettier and want to preserve their own style.

Is this primarily for making the code more easily readable in the editor itself?

**Comment by lewisf** [comment]
Yeah, I think its super helpful for that. I find that my co-workers and write and share codemods we're working on within it and it'd be nice to have the code be more readable as a toggleable option.

**Comment by lewisf** [comment]
@fkling what would seem like a sensible implementation for this?

is there room for this to be a hidden feature that is toggleable by some runtime variable that could be set in the JS console? or would you prefer coming up with with a spot in the UI where this should exist?

**Comment by pksjce** [comment]
Hey I'd love for the transform editor to have formatting with prettier. I routinely write all my mods there and copy it to my files.
I would implement a toggle button at the top right corner of the transform box. @lewisf - I can help you review and complete this if you are available?

**Comment by fkling** [comment]
I have two suggestions:

- Make `prettier` available inside the transform, so if someone wants to use it they could do `return pretter.format(....)` OR
- Similar to @pksjce's suggestion, but instead of adding the button to the transform editor, add it over the *output editor*.

**Comment by lewisf** [comment]
@fkling i think we'd want it to format in the transform editor as you type so that editing a codemod within the transform editor will maintain prettier's formatting.

it doesn't look like there would be as much value from applying the prettier transform on the output, since if someone wanted to use that output, they could copy it into their project and run prettier on their own.

**Comment by fkling** [comment]
Oh I somehow forgot that this was about the transform code itself. Sorry.

**Comment by lewisf** [comment]
@pksjce I don't have time immediately to continue this work -- if you want to take it over that'd be great! if not, I can try to get to it this weekend or next weekend.

**Comment by pksjce** [comment]
@lewisf - I can pick this up. How'd you want to do it? Can you add me as a collaborator or something?

**Comment by lewisf** [comment]
@pksjce just sent you collab rights on my fork, thanks!

**Comment by pksjce** [comment]
@lewisf - Thanks!
@fkling - Hey. I have one question. Why is there one `JSCodeshiftEditor` and an `Editor` component? In this solution, the `Transformer` for `babel` etc will not get the `prettier` support.

**Comment by fkling** [comment]
`JSCodeshiftEditor` extends `Editor`. It loads in a whole bunch of tern stuff for code completion that isn't necessary for other tools.

**Comment by pksjce** [comment]
So, shouldn't I add this `prettier` option to `Editor` itself?

**Comment by pksjce** [comment]
Hey this works now. Would love a review from you!

screen shot 2017-05-13 at 9 01 12 pm

**Comment by lewisf** [comment]
Oh, excited for this. Thanks for working on it @pksjce!

**Comment by pksjce** [comment]
Hey! @fkling - Would love a review on this. I have completed it from my end and have provided the screenshot above :)

**Comment by fkling** [comment]
Looks pretty good, thank you! I was wondering if you think whether there is a need for being able to prettify the "input" code itself (upper left editor) or not? Because if yes, then we could move the button into the `Editor` component itself so that it becomes available to all `Editor` instances.

Thoughts?

**Comment by pksjce** [comment]
Well, the code on top left and bottom right is kind of third party code right, which is not actively edited by the user. At least I don't actively edit it. I simply paste example type of code.
Only this transform editor is where I actually write many lines of code and without some auto formatting I struggle a lot to match all the brackets and parenthesis. This is the pain point I want to solve. Though if someone else from the community seconds you, I'm open to moving the button into the main toolbar.

**Comment by kentcdodds** [comment]
Might be even better if jscodeshift added support for prettier. I would hate to have someone think that they got a really nice codemod written up only to find that when they ran it on their code it messed things up...

**Comment by kentcdodds** [comment]
Either way though, having a toggle could indicate that prettier is unavailable normally...

**Comment by pksjce** [comment]
@kentcdodds- this only allows you to format the codemod editor. It doesn't get involved with the source or transformed code. Those parts still use whichever printer jscodeshift or babel uses

**Comment by fkling** [comment]
@kentcdodds People can already use prettier in their own codemods. They just need to require it and `return prettier.format(whatever);`. But I agree that jscodeshift should support a way to customize printing that is independent of the codemod itself.

**Comment by fkling** [comment]
Lets go ahead with this and update if necessary. Thank you!

**Comment by fkling** [comment]
After trying it I'm thinking maybe it should just be a button that prettifies the code on click. The blur behavior is kind of obscure and doesn't really improve UX over just clicking a button?

**Comment by pksjce** [comment]
Oh you merged it! Actually I was thinking the same thing today. There is no format on save for that editor. But blur is no different than formatting it on button click no? Still its nicer to be explicit. I can raise another PR to do it?

**Comment by pksjce** [comment]
On thinking more, how about if we apply prettier to the mod when return button is pressed?
But would it displace user's cursor position? I'll try this out today and tell you.

**Pull request merged**
