### PR TITLE
Update babylon to 6.9.0

### PR DESCRIPTION
**Pull request by danez**
Is it intended to also commit records.json? Wasn't sure why it changed

### CODE REVIEW

**Comment by fkling** [comment]
> Is it intended to also commit records.json?

I haven't thought about it yet. I'm not even sure whether it's that useful. But lets say yes for the time being.

Thanks!

**Comment by hzoo** [comment]
Nice, there were a good amount of bug fixes (like the exponentiation operator issue)

**Comment by fkling** [comment]
I forgot to update the local packages *facepalm*.

**Comment by hzoo** [comment]
yea although acorn-to-esprima isn't really updated.. I moved the logic back into babel-eslint since it was annoying and no one else was using the package at the time.

**Comment by fkling** [comment]
I see... should we replace it with babel-eslint then? Or remove it? I have to confess that I'm confused about the dependencies between acorn-to-esprima, and eslint1 and eslint2.

**Comment by hzoo** [comment]
acorn-to-esprima is just a separate module I made out of babel-eslint that did what the name was.

However, it was annoying to modify in a separate repo so I just stopped updating that. It is necessary because eslint used espree/esprima. However now espree is actually a wrapper around acorn (which is crazy because babel-eslint is doing the same thing as espree).

babel-eslint: babylon parser -> a lot of hacks + convert expreimental syntax into something else -> convert acorn tokens to esprima -> eslint.

I think the issue was that using babel-eslint had issues or something about the bundle being big I forgot

**Comment by fkling** [comment]
@hzoo: Bundle being big could probably be avoided through wepback configuration.

To me it sounds like we should just try to replace acorn-to-esprima here with the latest version of babel-eslint.

**Pull request merged**
