### PR TITLE
Update glimmer packages to 0.25.1.

### PR DESCRIPTION
**Pull request by rwjblue**
The format of the AST transforms changed, this adjusts to the new format.

### CODE REVIEW

**Comment by RReverser** [comment]
Hmm I'm not sure what we want to do in these cases, given that there might be saved snippets that rely on the old API.

@fkling Do we really want to preserve old snippets working forever? We might easily blow up tools x versions matrix that way (no offence to the on-demand tool builder approach).

**Comment by Turbo87** [comment]
@RReverser would it be possible to have both versions in parallel for a while and display some sort of warning for the old version?

**Comment by rwjblue** [comment]
I believe that I could do `packages/glimmer-0-24` and `packages/glimmer-0-25`, but I'm not sure the gists have enough meta data to know which version they were built against...

**Comment by RReverser** [comment]
Yeah, the old Glimmer currently would have to be preserved as the only "glimmer" to preserve compatibility and new one would have to be versioned...

**Comment by fkling** [comment]
> Do we really want to preserve old snippets working forever?

Isn't that how the web is supposed to work? 😉 

Idk, I saw astexplorer similar to jsfiddle and you wouldn't want old jsfiddles to break would you?

Building older versions on demand would make this a bit better but of course it also introduces additional complexity.

Alternatively, since we are already storing the version of the parser, we could show a warning that the snippet was created with an older version and explain that results might differ or transforms might be broken. But overall that seems like a bad user experience.

**Comment by RReverser** [comment]
@fkling 

> Idk, I saw astexplorer similar to jsfiddle and you wouldn't want old jsfiddles to break would you?

I guess here's the difference - I mostly see it as a debugging sort of tool that you might want to share with other people to reproduce some issues or play with transformer idea, but when it's done, never come back :) JSFiddle, on the other hand, is more for long-term visual demos rather than debugging sessions.

> So alternatively we could show a warning that the snippet was created with an older version and explain that results might differ or transforms might be broken. But overall that seems like a bad user experience.

Or we could auto-run codemods when such snippet is opened :)

**Comment by fkling** [comment]
@RReverser 

> but when it's done, never come back

idk, I can imagine people referencing codemods in astexplorer in blog posts and such.

Anyways, I'm not saying that multi-version support is something we absolutely must implement now, but we shouldn't do anything that prevents us from adding it in the future.

**Comment by fkling** [comment]
How should we proceed?

**Comment by rwjblue** [comment]
@fkling - I need to update for @glimmer/compiler@0.26.x (which released a short while after I submitted this).

Also, I am happy to update to support versioned glimmer versions.

**Comment by fkling** [comment]
If you don't want to support older versions that's OK for me. So, should I merge this before you make any other updates?

**Comment by fkling** [comment]
@rwjblue: Could you update this PR to be compatible with the latest version of glimmer and then I'l;l merge it? Thank you!

**Comment by rwjblue** [comment]
Absolutely! I’ll try to have this updated this week...

**Comment by fkling** [comment]
Superseded by #287

**Pull request closed without merging**
