### PR TITLE
Update flow-parser to 0.113

### PR DESCRIPTION
**Pull request by gkz**
Tested by running:
```
cd website && yarn install && yarn run build-dev && yarn run start
```
And playing around locally.

### CODE REVIEW

**Comment by fkling** [comment]
Thank you!

**Comment by fkling** [comment]
Unfortunately the prod build is broken somehow (https://staging.astexplorer.net/). Selecting flow gives `e.parse` is not a function.

It works on https://mater.astexplorer.net/, so it must have something to do with minification.

**Comment by fkling** [comment]
Not sure what exactly happens in the webpack build process, but I believe export related stuff in the flow parser is rewritten in a way that brakes.
I tried to exclude the flow parser from being minified (since it already is minified), but that didn't change anything. Maybe I did it incorrectly.
Will continue to look into it :disappointed:

**Comment by gkz** [comment]
I tested with `yarn build-dev`, that didn't hit the issue.

Feel free to revert this change for now if you can't fix it.

**Comment by fkling** [comment]
Yeah, I will revert for now and will investigate more later... sorry for that :disappointed:

**Pull request merged**
