### PR TITLE
log error.stack

### PR DESCRIPTION
**Pull request by hzoo**
screen shot 2016-11-15 at 9 05 26 am

to be able to click on the code

### CODE REVIEW

**Comment by fkling** [comment]
Does `console.error(error);` not let you click through the call stack?

**Comment by hzoo** [comment]
Yeah I believe it was just a string at the time I tried this

**Comment by fkling** [comment]
This is what I am getting when I add `new Error('...')` in the transform function:

screen shot 2016-12-29 at 5 31 56 pm

Looks like it works fine as it is?

**Comment by hzoo** [comment]
just going to close for now

**Pull request closed without merging**
