### PR TITLE
Add Hyntax Html Parser

### PR DESCRIPTION
**Pull request by nik-garmash**
Hi! This is my html parser implementation, would be nice to have it here.

### CODE REVIEW

**Comment by j-f1** [comment]
Can you fix the merge conflict in `yarn.lock`?

**Comment by nik-garmash** [comment]
Done

**Comment by nik-garmash** [comment]
Seems like uglify-js cannot minify the code. Do I need to have an es5 transpiled version in my package?

**Comment by nik-garmash** [comment]
Hi, I added es5 version into the package

**Comment by nik-garmash** [comment]
Updated parser version and rebased. @fkling

**Comment by nik-garmash** [comment]
Updated parser version, rebased and fixed conflicts.

**Comment by fkling** [comment]
Sorry for ignoring this PR for so long :disappointed:

**Comment by nik-garmash** [comment]
Thank you!

**Pull request merged**
