### PR TITLE
Store parser settings in snippets

### PR DESCRIPTION
**Pull request by fkling**
This makes sharing settings more consistent. Instead of using the
locally stored parser settings, the snippet parser settings will be
used.

Note however that any changes to settings after a snippet was loaded
will replace the locally stored settings. This might make settings
behavior a little less predictable.

Also note that it's not clear yet what impact stored settings will have
when the corresponding parser is updated and the available options
change.

This would kind of solve #115 and #55 (instead of storing the settings in the URL).

Making a PR to get some feedback on the general idea.

### CODE REVIEW

**Comment by fkling** [comment]
I guess nobody cares too much about this :P

**Comment by hzoo** [comment]
I care 😢, maybe not everyone actually watches repos (you should ping the creators of the issues)

> Note however that any changes to settings after a snippet was loaded
will replace the locally stored settings. 

Maybe need to add a notification somewhere saying that the snippet/url changed the settings

Also note that it's not clear yet what impact stored settings will have
when the corresponding parser is updated and the available options
change.

> So if we removed an option in the parser and it tries to set it, or the option takes a different value and tries to set it?

**Comment by fkling** [comment]
> So if we removed an option in the parser and it tries to set it, or the option takes a different value and tries to set it?

Yep.

---

Maybe I have to rethink the configuration system a little so that it is possible to have "your" (local) settings and have "snippet settings".

**Comment by fkling** [comment]
Did a lot of changes to the internal app state, see commit message. Will try to merge this tomorrow.

**Comment by fkling** [comment]
Since this makes changes to the parse backend but we are moving away from parse, I'm going to merge this into new working branch for moving over gists.

**Comment by fkling** [comment]
This was implemented with 5745dbd127c0d4fdcfd786937aa6096e65982fb7 .

**Pull request closed without merging**
