### PR TITLE
Add wireformat view for glimmer transform

### PR DESCRIPTION
**Pull request by Turbo87**
screenshot

This PR also introduces the possibility to return a POJO from the transformer and have it displayed inside the `JSONEditor` component.

/cc @fkling @mmun

### CODE REVIEW

**Comment by fkling** [comment]
Sorry for the late reply. I like the idea of returning an object from the transformer and showing it in the JSON view! This could be useful for other transformers too!

I was wondering whether it is necessary to add a new transformer though. I think it would be more convenient if the existing transform could handle both cases. However, it looks like that would require being able to configure the transformer somehow, which is currently not possible, but which is something that has come up before.

If this PR can wait a little I could take a stab at that after this week (after #184 is done).

**Comment by Turbo87** [comment]
> I was wondering whether it is necessary to add a new transformer though. I think it would be more convenient if the existing transform could handle both cases. However, it looks like that would require being able to configure the transformer somehow, which is currently not possible, but which is something that has come up before.

yes, that would've certainly been a better way.

> If this PR can wait a little

I'm certainly not in a rush, but you could also merge this and then you'd have something to refactor once you get around to implementing transformer configs. I'm fine either way. Thanks again for working on this awesome tool! :)

**Comment by Turbo87** [comment]
@fkling rebased to fix conflicts

**Comment by fkling** [comment]
👍 

I think we'll be able to consolidate both transforms in the future without being to hacky.

**Comment by mmun** [comment]
Awesome!

**Pull request merged**
