### PR TITLE
New: ESLint v4

### PR DESCRIPTION
**Pull request by gyandeeps**
Question:

* Should we remove ESLint v1?
* Maybe v2 also?

### CODE REVIEW

**Comment by RReverser** [comment]
Been thinking about removing ESLint v1/v2 too. I'm currently undertaking a generic cleanup of ASTExplorer, if you want, I can remove them as part of it too.

**Comment by fkling** [comment]
I'd advocate for hiding them from the menu, but not completely removing them. Older shared snippets might rely on them.

I guess the general question is: Do we want to make old snippets work continue to work and/or is it worth it?

That's one of the reason why I started working on #197.

**Comment by gyandeeps** [comment]
Sounds good.
I think this PR is ready from side. regardless of v1/v2 convo this PR can still go on.

**Comment by hzoo** [comment]
if it's not that hard to maintain can just leave it unless someone really wants to remove?

**Comment by RReverser** [comment]
@hzoo Yeah but they contribute to the chunks sizes, and keeping them means periodically ensuring that they don't bloat up chunks with important JS.

> Do we want to make old snippets continue to work and/or is it worth it?

@fkling Should we make this a poll on Twitter or something?

**Comment by RReverser** [comment]
Btw, are there any major API incompatibilities for plugins between ESLint v1..v4? Or can we just auto-switch to the new ESLint for old snippets?

**Comment by gyandeeps** [comment]
We dont use plugins in here, are you asking about rules?

**Comment by RReverser** [comment]
Yeah, custom rules (aren't they usually shipped as plugins in ESLint?).

**Comment by gyandeeps** [comment]
Right, but here we dont have to worry about that aspect as we directly tell eslint to load a rule by giving it a name and the object.
Outer object structure is same across version (as per my memory) but internal methods provided and their implementations have changed. ie the methods on the arguments provided to each node type listeners in the rule.

**Comment by RReverser** [comment]
@gyandeeps I see, so we can't just swap them...

**Comment by gyandeeps** [comment]
I think so... Maybe in some cases the inner workings of the rules might break based on certain other functionality changes..

**Comment by fkling** [comment]
I think it would make sense to only expose the latest version in the frontend but be able to build/serve older versions as needed. The work that I started in #197 would allow us to do that.
I'm planning to continue working on this soon.

In 95c53e5fc9e01d93e8cff96ad5bf78738ec1a8b2 I added the ability to hide parsers/tools from the menu which is what we can do for the different eslint versions for now.

**Comment by fkling** [comment]
Looking at the changes to the lock file (https://gist.github.com/fkling/26a3ad59b43eab66a2065883bb8bfa83) it seems there are a couple of dependencies added (and therefore probably bundled) that are CLI related and therefore not necessary?

Might be worth updating `webpack.config.js` somehow to ignore those.

**Comment by RReverser** [comment]
Actually this breaks production build (reminds me the reason I wanted to use it for Travis in #243, cc @josephfrazier):

```
ERROR in ./~/eslint4/~/eslint/lib/util/source-code.js
Module build failed: SyntaxError: Unexpected token name «i», expected punc «;»
    at JS_Parse_Error.get (eval at <anonymous> (/Users/rreverser/oss/astexplorer/website/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:86:23)
    at new ModuleBuildError (/Users/rreverser/oss/astexplorer/website/node_modules/webpack/lib/ModuleBuildError.js:18:42)
    at runLoaders (/Users/rreverser/oss/astexplorer/website/node_modules/webpack/lib/NormalModule.js:192:19)
    at /Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/rreverser/oss/astexplorer/website/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/rreverser/oss/astexplorer/website/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/rreverser/oss/astexplorer/website/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:490:3)
 @ ./~/eslint4/index.js 1:87-125
 @ ./src/parsers/js/transformers/eslint4/index.js
 @ ./src/parsers ^\.\/(?!utils)[^\/]+\/(transformers\/([^\/]+)\/)?(codeExample\.txt|[^\/]+?\.js)$
 @ ./src/parsers/index.js
 @ ./src/storage/gist.js
 @ ./src/app.js

ERROR in ./~/eslint4/~/eslint/lib/linter.js
Module build failed: SyntaxError: Unexpected token: operator (>)
    at JS_Parse_Error.get (eval at <anonymous> (/Users/rreverser/oss/astexplorer/website/node_modules/uglify-js/tools/node.js:1:1), <anonymous>:86:23)
    at new ModuleBuildError (/Users/rreverser/oss/astexplorer/website/node_modules/webpack/lib/ModuleBuildError.js:18:42)
    at runLoaders (/Users/rreverser/oss/astexplorer/website/node_modules/webpack/lib/NormalModule.js:192:19)
    at /Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at runSyncOrAsync (/Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:229:2)
    at Array.<anonymous> (/Users/rreverser/oss/astexplorer/website/node_modules/loader-runner/lib/LoaderRunner.js:202:4)
    at Storage.finished (/Users/rreverser/oss/astexplorer/website/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at /Users/rreverser/oss/astexplorer/website/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9
    at /Users/rreverser/oss/astexplorer/website/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:490:3)
 @ ./~/eslint4/index.js 1:13-41
 @ ./src/parsers/js/transformers/eslint4/index.js
 @ ./src/parsers ^\.\/(?!utils)[^\/]+\/(transformers\/([^\/]+)\/)?(codeExample\.txt|[^\/]+?\.js)$
 @ ./src/parsers/index.js
 @ ./src/storage/gist.js
 @ ./src/app.js
```

**Comment by RReverser** [comment]
@fkling Hmm, but you pushed the new website - did this error occur during build for you too? (it doesn't cause WebPack to fail, but does appear in logs and the corresponding file remains unminified)

**Comment by RReverser** [comment]
Actually, the reason is deeper - `eslint4` is left completely untranspiled in the production. Fixing now.

**Comment by gyandeeps** [comment]
sorry about this. I had no idea about all this. I would have done something if I had known about these issues. Thanks @RReverser :100:

**Comment by RReverser** [comment]
@gyandeeps No, that's okay, just something that needs to be detected and fixed on our side better.

**Comment by josephfrazier** [comment]
> Actually this breaks production build (reminds me the reason I wanted to use it for Travis in #243, cc @josephfrazier)

Ah, I guess we should switch that over.

**Comment by RReverser** [comment]
Fixed in https://github.com/fkling/astexplorer/commit/dcdcae52eaae4f182ae3f19b8c34fdb3c7b168d7

**Comment by RReverser** [comment]
@josephfrazier @fkling  I've added two different `env` to let Travis run `NODE_ENV=development` and `NODE_ENV=production` versions in parallel. This should be enough to reproduce these kinds of issues and shouldn't slow down us too much.

81168f73-be72-4ca5-b127-b45c02fb48f9

**Comment by fkling** [comment]
Uh I fixed that locally but I guess I forgot to push my changes.

**Comment by josephfrazier** [comment]
You'll probably want to use `yarn install --production=false` in the install script, to ensure that all the build dependencies are still pulled in. See https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-production

**Comment by RReverser** [comment]
@josephfrazier Ah yeah makes sense...

**Comment by RReverser** [comment]
@josephfrazier Thanks for the tip, trying: https://travis-ci.org/fkling/astexplorer/builds/245440814

**Comment by josephfrazier** [comment]
Sure thing @RReverser, glad to see it's working now (with a README badge, too)!

**Pull request merged**
