### PR TITLE
update to TypeScript 2.3

### PR DESCRIPTION
**Pull request by mohsen1**

### CODE REVIEW

**Comment by RReverser** [comment]
@fkling Would it perhaps make sense to turn on Greenkeeper for this project so that such PRs would come automatically on each update?

**Comment by mohsen1** [comment]
That would be nice!

**Comment by fkling** [comment]
I'll look into that tonight!

**Comment by fkling** [comment]
So, I enabled greenkeeper, but it might not actually work if the package.json file is not in the root? Or everything is up-to-date 😛

**Comment by RReverser** [comment]
@fkling Huh, apparently not :( https://github.com/greenkeeperio/greenkeeper/issues/139

Any reason not to have it and other configs at the root though?

**Comment by fkling** [comment]
Mmh... I guess not. I just thought it's cleaner this way.

**Comment by RReverser** [comment]
Probably... although there are few config files in the root already, shouldn't hurt too much :P

**Comment by RReverser** [comment]
Oh I see, there are separate package.json's for different folders, so this is indeed the monorepo case.

**Comment by RReverser** [comment]
Then there are only two ways: create org for astexplorer (and add us all :D) with separate repos per project (server/website/...) or continue updating things manually for now...

**Pull request merged**
