### PR TITLE
feat(parser): add swc support via @swc/wasm-web

### PR DESCRIPTION
**Pull request by kwonoj**
This PR is one additional attempt to #555 for adding swc's parser into ast explorer.

I am aware there are prior attempts like https://github.com/fkling/astexplorer/pull/556 or https://github.com/fkling/astexplorer/pull/602 and given that both have not landed, honestly not sure if this PR is feasible to land. Also, feel free to close if the original PR https://github.com/fkling/astexplorer/pull/556 should be updated instead.

This PR attempts to preserve existing build as much, instead apply some workaround to bend over `@swc/wasm-web` to work with webpack@4. swc's web target build is for non-bundler cases which webpack@4 doesn't support some of the syntax. Change workarounds it via manually injecting path to the wasm binary.

Other changes are quite straightforward to follow contributing guidelines Local testing seems most features are working, however there maybe some unknown things need to be fix forward.

### CODE REVIEW

**Comment by fkling** [comment]
Thank you for taking a stab at this. I'll take a look at this more closely next week. It's unfortunate that workaround are necessary to make it work with webpack@v4, but upgrading to webpack@v5 is probably too big of an effort at the moment.

**Comment by jantimon** [comment]
Right now we are developing SWC Plugins and would love to use ASTExplorer as a tool - are there any blockers for this PR which we could support?

**Comment by fkling** [comment]
Everything looked fine. The website has been updated.

**Comment by jantimon** [comment]
thanks felix 🎉

**Pull request merged**
