### PR TITLE
[RegExp] Implement transformer for regexp-tree

### PR DESCRIPTION
**Pull request by DmitrySoshnikov**
This exposes `transform` API for `regexp-tree` parser.

### CODE REVIEW

**Comment by DmitrySoshnikov** [comment]
Not sure why `Add RegExp parser (e568a99)` commit was added, it's already merged to master. The only change is the `0996641` commit.

**Comment by RReverser** [comment]
@DmitrySoshnikov Because it's rebased and has a different SHA on master. Just rebase your PR, that should strip it.

**Comment by DmitrySoshnikov** [comment]
@RReverser, ah, makes sense, sorry; rebased.

**Comment by RReverser** [comment]
Looks like you merged master into your branch instead of rebasing on top of it, so now there are 5 commits 😄 Guess you want to squash them.

**Comment by DmitrySoshnikov** [comment]
@RReverser, sigh.. :)

@fkling, can we just pick the `0996641` from the PR, it basically contains all the changes for it?

**Comment by fkling** [comment]
Merged: 962f89cc33f0dc6061ceb82b69ee5396fd16186d

**Pull request closed without merging**
